# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Build
          command: |
            apt update && apt upgrade -y && apt install sudo -y
            sudo apt install build-essential git file patch perl tar wget cpio unzip rsync bc -y
            make -j$(nproc --all)
            git config --global user.name "Harsh Barsaiyan"
            git config --global user.email "hbarsaiyan@gmail.com" 
            export GITHUB_TOKEN=$(echo $GH_TOKEN)
            sudo apt install npm
            cd output/images
            export iso_path=$(ls *iso* | tail -n -1)
            github-release "hbarsaiyan/buildroot" "$iso_path" "master" "DahliaOS"
            exit 1
            
